baseurl = "https://www.cheesena.dev/"
title = "ちーずな雑記"
theme = "hugo_theme_robust"

googleAnalytics = "G-DRH61PDPF6"
disqusShortname = "cheesena"

[params]
description = "ねこになりたい"
dateformat = "Jan 2, 2006" # Optional
# Fonts settings.
googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
logofontfamily = "Lobster, cursive" # Optional, Override logo font.

enableHighlight = true # highlight.js option

[params.author]
thumbnail = "images/author.jpg"
name = "cheeseNA"
description = "<a href='https://www.ee.t.u-tokyo.ac.jp/j/'>EEIC</a> 2年生です. コンピュータサイエンス等勉強してます."
# facebook = "https://www.facebook.com/daisuke.tsuji.735"
twitter = "https://twitter.com/_cheeseNA"
github = "https://github.com/cheeseNA"

[outputs]
page = [ "HTML", "AMP" ] # if you want AMP enable.